import 'package:flutter/material.dart';
import '../models/service_category.dart';
import '../models/service_provider.dart';

class DataService {
  static final List<ServiceCategory> _categories = [
    ServiceCategory(
      name: 'Hotels',
      icon: Icons.hotel,
      color: Colors.orange,
      serviceCount: 15,
    ),
    ServiceCategory(
      name: 'Taxi/Auto',
      icon: Icons.local_taxi,
      color: Colors.green,
      serviceCount: 28,
    ),
    ServiceCategory(
      name: 'Mechanics',
      icon: Icons.build,
      color: Colors.red,
      serviceCount: 18,
    ),
    ServiceCategory(
      name: 'Electricians',
      icon: Icons.electrical_services,
      color: Colors.amber,
      serviceCount: 22,
    ),
    ServiceCategory(
      name: 'Plumbers',
      icon: Icons.plumbing,
      color: Colors.blue,
      serviceCount: 12,
    ),
    ServiceCategory(
      name: 'Cleaners',
      icon: Icons.cleaning_services,
      color: Colors.purple,
      serviceCount: 9,
    ),
  ];

  static final List<ServiceProvider> _allServices = [
    // Hotels (15 services)
    ServiceProvider(
      name: 'Royal Palace Hotel',
      category: 'Hotels',
      description:
          'Luxury accommodation with modern amenities and excellent service',
      phone: '+91 9876543210',
      location: 'MG Road, Kozhikode',
      rating: 4.8,
      isVerified: true,
      image: '🏨',
    ),
    ServiceProvider(
      name: 'Grand Plaza Hotel',
      category: 'Hotels',
      description:
          'Comfortable stay with excellent service and convenient location',
      phone: '+91 9876543211',
      location: 'Beach Road, Kozhikode',
      rating: 4.5,
      isVerified: true,
      image: '🏨',
    ),
    ServiceProvider(
      name: 'Budget Inn',
      category: 'Hotels',
      description: 'Affordable accommodation for travelers and business guests',
      phone: '+91 9876543212',
      location: 'Railway Station, Kozhikode',
      rating: 4.2,
      isVerified: false,
      image: '🏨',
    ),
    ServiceProvider(
      name: 'Malabar Palace',
      category: 'Hotels',
      description: 'Traditional Kerala hospitality with modern facilities',
      phone: '+91 9876543213',
      location: 'Palayam, Kozhikode',
      rating: 4.7,
      isVerified: true,
      image: '🏨',
    ),
    ServiceProvider(
      name: 'Sea View Resort',
      category: 'Hotels',
      description: 'Beachfront location with stunning ocean views',
      phone: '+91 9876543214',
      location: 'Kappad Beach, Kozhikode',
      rating: 4.6,
      isVerified: true,
      image: '🏨',
    ),
    ServiceProvider(
      name: 'City Center Lodge',
      category: 'Hotels',
      description: 'Budget-friendly option in the heart of the city',
      phone: '+91 9876543215',
      location: 'SM Street, Kozhikode',
      rating: 4.0,
      isVerified: false,
      image: '🏨',
    ),
    ServiceProvider(
      name: 'Heritage Hotel',
      category: 'Hotels',
      description: 'Colonial architecture with modern comfort',
      phone: '+91 9876543216',
      location: 'Civil Station, Kozhikode',
      rating: 4.4,
      isVerified: true,
      image: '🏨',
    ),
    ServiceProvider(
      name: 'Business Inn',
      category: 'Hotels',
      description: 'Perfect for business travelers with conference facilities',
      phone: '+91 9876543217',
      location: 'Hilite City, Kozhikode',
      rating: 4.3,
      isVerified: true,
      image: '🏨',
    ),
    ServiceProvider(
      name: 'Backwater Resort',
      category: 'Hotels',
      description: 'Serene location near backwaters with nature views',
      phone: '+91 9876543218',
      location: 'Kadalundi, Kozhikode',
      rating: 4.5,
      isVerified: false,
      image: '🏨',
    ),
    ServiceProvider(
      name: 'Airport Hotel',
      category: 'Hotels',
      description: 'Convenient location near Calicut Airport',
      phone: '+91 9876543219',
      location: 'Karipur, Kozhikode',
      rating: 4.1,
      isVerified: true,
      image: '🏨',
    ),
    ServiceProvider(
      name: 'Family Guest House',
      category: 'Hotels',
      description: 'Homely atmosphere perfect for families',
      phone: '+91 9876543220',
      location: 'West Hill, Kozhikode',
      rating: 4.2,
      isVerified: false,
      image: '🏨',
    ),
    ServiceProvider(
      name: 'Luxury Suites',
      category: 'Hotels',
      description: 'Premium suites with personalized service',
      phone: '+91 9876543221',
      location: 'Medical College, Kozhikode',
      rating: 4.9,
      isVerified: true,
      image: '🏨',
    ),
    ServiceProvider(
      name: 'Travellers Rest',
      category: 'Hotels',
      description: 'Clean and comfortable accommodation for budget travelers',
      phone: '+91 9876543222',
      location: 'Bus Stand, Kozhikode',
      rating: 3.9,
      isVerified: false,
      image: '🏨',
    ),
    ServiceProvider(
      name: 'Garden View Hotel',
      category: 'Hotels',
      description: 'Peaceful location with beautiful garden surroundings',
      phone: '+91 9876543223',
      location: 'Vellimadukunnu, Kozhikode',
      rating: 4.4,
      isVerified: true,
      image: '🏨',
    ),
    ServiceProvider(
      name: 'Executive Stay',
      category: 'Hotels',
      description: 'Modern amenities for the discerning business traveler',
      phone: '+91 9876543224',
      location: 'Bypass Road, Kozhikode',
      rating: 4.6,
      isVerified: true,
      image: '🏨',
    ),

    // Taxi/Auto (28 services)
    ServiceProvider(
      name: 'Ravi Auto Service',
      category: 'Taxi/Auto',
      description: '24/7 available, honest pricing and reliable service',
      phone: '+91 8765432109',
      location: 'Bus Stand, Kozhikode',
      rating: 4.6,
      isVerified: true,
      image: '🚗',
    ),
    ServiceProvider(
      name: 'Quick Taxi',
      category: 'Taxi/Auto',
      description: 'Fast and reliable taxi service across the city',
      phone: '+91 8765432110',
      location: 'City Center, Kozhikode',
      rating: 4.4,
      isVerified: true,
      image: '🚗',
    ),
    ServiceProvider(
      name: 'Auto Rickshaw Union',
      category: 'Taxi/Auto',
      description: 'Local auto rickshaw service with fair pricing',
      phone: '+91 8765432111',
      location: 'Market Area, Kozhikode',
      rating: 4.1,
      isVerified: false,
      image: '🚗',
    ),
    ServiceProvider(
      name: 'City Cab Services',
      category: 'Taxi/Auto',
      description: 'Professional cab service for long distance travel',
      phone: '+91 8765432112',
      location: 'Railway Station, Kozhikode',
      rating: 4.5,
      isVerified: true,
      image: '🚗',
    ),
    ServiceProvider(
      name: 'Tourist Taxi',
      category: 'Taxi/Auto',
      description: 'Specialized in tourist packages and sightseeing',
      phone: '+91 8765432113',
      location: 'Beach Road, Kozhikode',
      rating: 4.7,
      isVerified: true,
      image: '🚗',
    ),
    // Add more taxi services...
    ServiceProvider(
      name: 'Metro Auto Stand',
      category: 'Taxi/Auto',
      description: 'Organized auto stand with digital booking',
      phone: '+91 8765432114',
      location: 'Metro Station, Kozhikode',
      rating: 4.2,
      isVerified: false,
      image: '🚗',
    ),

    // Electricians (22 services)
    ServiceProvider(
      name: 'Kumar Electronics',
      category: 'Electricians',
      description:
          'Expert in home & commercial wiring with 15+ years experience',
      phone: '+91 7654321098',
      location: 'Palayam, Kozhikode',
      rating: 4.9,
      isVerified: true,
      image: '⚡',
    ),
    ServiceProvider(
      name: 'Power Solutions',
      category: 'Electricians',
      description: 'Electrical repairs and installations for all needs',
      phone: '+91 7654321099',
      location: 'SM Street, Kozhikode',
      rating: 4.7,
      isVerified: true,
      image: '⚡',
    ),
    ServiceProvider(
      name: 'Voltage Experts',
      category: 'Electricians',
      description: 'Specialized in industrial electrical work',
      phone: '+91 7654321100',
      location: 'Industrial Estate, Kozhikode',
      rating: 4.8,
      isVerified: true,
      image: '⚡',
    ),
    ServiceProvider(
      name: 'Home Electric Service',
      category: 'Electricians',
      description: 'Residential electrical services and emergency repairs',
      phone: '+91 7654321101',
      location: 'West Hill, Kozhikode',
      rating: 4.5,
      isVerified: false,
      image: '⚡',
    ),
    ServiceProvider(
      name: 'Smart Electrical Works',
      category: 'Electricians',
      description: 'Modern electrical solutions and smart home installations',
      phone: '+91 7654321102',
      location: 'Medical College, Kozhikode',
      rating: 4.6,
      isVerified: true,
      image: '⚡',
    ),

    // Mechanics (18 services)
    ServiceProvider(
      name: 'Auto Repair Center',
      category: 'Mechanics',
      description: 'Complete vehicle servicing and repair for all brands',
      phone: '+91 6543210987',
      location: 'Bypass Road, Kozhikode',
      rating: 4.6,
      isVerified: true,
      image: '🔧',
    ),
    ServiceProvider(
      name: 'Bike Service Point',
      category: 'Mechanics',
      description: 'Specialized in two-wheeler repairs and maintenance',
      phone: '+91 6543210988',
      location: 'Link Road, Kozhikode',
      rating: 4.3,
      isVerified: false,
      image: '🔧',
    ),
    ServiceProvider(
      name: 'Car Care Center',
      category: 'Mechanics',
      description: 'Premium car servicing with genuine spare parts',
      phone: '+91 6543210989',
      location: 'NH Bypass, Kozhikode',
      rating: 4.7,
      isVerified: true,
      image: '🔧',
    ),
    ServiceProvider(
      name: 'Express Auto Service',
      category: 'Mechanics',
      description: 'Quick repairs and emergency breakdown service',
      phone: '+91 6543210990',
      location: 'Airport Road, Kozhikode',
      rating: 4.4,
      isVerified: true,
      image: '🔧',
    ),

    // Plumbers (12 services)
    ServiceProvider(
      name: 'Aqua Fix Solutions',
      category: 'Plumbers',
      description:
          'Professional plumbing services for residential and commercial',
      phone: '+91 5432109876',
      location: 'Civil Station, Kozhikode',
      rating: 4.8,
      isVerified: true,
      image: '🔧',
    ),
    ServiceProvider(
      name: 'Pipe Masters',
      category: 'Plumbers',
      description: 'Expert in pipeline installation and water system repairs',
      phone: '+91 5432109877',
      location: 'Palayam, Kozhikode',
      rating: 4.5,
      isVerified: false,
      image: '🔧',
    ),
    ServiceProvider(
      name: 'Drain Doctor',
      category: 'Plumbers',
      description: '24/7 emergency plumbing and drain cleaning service',
      phone: '+91 5432109878',
      location: 'Beach Road, Kozhikode',
      rating: 4.6,
      isVerified: true,
      image: '🔧',
    ),

    // Cleaners (9 services)
    ServiceProvider(
      name: 'Clean Home Services',
      category: 'Cleaners',
      description: 'Professional house cleaning and deep cleaning services',
      phone: '+91 4321098765',
      location: 'West Hill, Kozhikode',
      rating: 4.5,
      isVerified: true,
      image: '🧹',
    ),
    ServiceProvider(
      name: 'Sparkle Cleaning',
      category: 'Cleaners',
      description: 'Office and commercial space cleaning specialists',
      phone: '+91 4321098766',
      location: 'Business District, Kozhikode',
      rating: 4.7,
      isVerified: true,
      image: '🧹',
    ),
    ServiceProvider(
      name: 'Eco Clean Solutions',
      category: 'Cleaners',
      description: 'Eco-friendly cleaning services for homes and offices',
      phone: '+91 4321098767',
      location: 'Medical College, Kozhikode',
      rating: 4.4,
      isVerified: false,
      image: '🧹',
    ),
  ];

  static List<ServiceCategory> get categories => _categories;
  static List<ServiceProvider> get allServices => _allServices;

  static List<ServiceProvider> getServicesByCategory(String category) {
    return _allServices
        .where((service) => service.category == category)
        .toList();
  }

  static List<ServiceProvider> getFeaturedServices() {
    return _allServices
        .where((service) => service.isVerified && service.rating >= 4.5)
        .take(3)
        .toList();
  }
}
